### PR TITLE
bb-promster level in addIP

### LINKED ISSUE #28: Get bb-promster level to add an IP to an App
bb-bot isn't getting the bb-promster level to add an IP to an App. Since bb-promster uses the string /services-promster-ln to scrape paths when the level is higher than 1, bb-bot doesn't work for bb-promster with levels higher than 1.

### PR DESCRIPTION
**Pull request by KarineValenca**
Fix #28

### CODE REVIEW

File: src/db.js [hunk 1]
```diff
@@ -307,3 +309,11 @@ export function deleteSettings (settings) {
 export function deleteAll () {
 	return etcd.delete().all().exec()
 }
+
+function getServiceBaseUrl (promsterLevel) {
```
Comment (gutorc92) [inline src/db.js:313]: @KarineValenca, ```getServiceBaseUrl ``` could be in App class then you could just change line 27 to:

``` await app.getIps().forEach(ip => addIp(app, ip)) ```

File: src/types/App.ts [hunk 2]
```diff
@@ -195,6 +207,7 @@ export default class App {
 		const deploymentManifest = require('../deployments/bb-promster.json')
 		const deploy = { ...deploymentManifest }
 		const etcdService = settings.getEtcdService()
+		const registryEtcdBase = this._level === 1 ? '/services' : `/services-promster-l${this._level}`
```
Comment (gutorc92) [inline src/types/App.ts:210]: @KarineValenca, why not not use ```getServiceBaseUrl ```?
